[tool.poetry]
name = "sd-fail-notify"
version = "19.12.0"
description = "Send a text message when a systemd process fails"
authors = ["Rick Henry <rickhenry@rickhenry.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rickh94/sd_fail_notify.git"
repository = "https://github.com/rickh94/sd_fail_notify.git"
exclude = ["test_config.toml"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.0"
twilio = "^6.33"
toml = "^0.10.0"
requests = "^2.22"

[tool.poetry.dev-dependencies]
faker = "^2.0"
pytest = "^5.3"

[tool.poetry.scripts]
sd-fail-notify = 'sd_fail_notify.main:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
