[tool.poetry]
name = "songkick"
version = "0.1.0"
description = "A Python SDK for the Songkick API."
authors = ["Craig Anderson <craiga@craiga.id.au>"]
readme = "README.markdown"


[tool.poetry.dependencies]
python = "^3.6"
requests = "^2"
python-dateutil = "^2.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "=19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
