[tool.poetry]
name = "repyl"
version = "0.1.1"
description = ""
authors = ["Ben G <ben.gordon@toasttab.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
yapf = "^0.28.0"
pylint = "^2.4"
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
