[tool.poetry]
name = "aws_assume"
version = "0.2.1"
description = "AWS session token refreshing daemon"
authors = ["Dick Marinus <dick@mrns.nl>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "7.0"
aws_credential_process = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
freezegun = "^0.3.12"
pytest-cov = "^2.8"
pylint = "^2.4"

[tool.poetry.scripts]
_assume = "aws_assume._assume:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
